package com.yuudati.securitydemo.dao;

import com.yuudati.securitydemo.pojo.SysRoleUrl;
import com.yuudati.securitydemo.pojo.SysRoleUrlExample;
import org.apache.ibatis.annotations.*;

import java.util.List;

public interface SysRoleUrlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_url
     *
     * @mbg.generated
     */
    long countByExample(SysRoleUrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_url
     *
     * @mbg.generated
     */
    int deleteByExample(SysRoleUrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_url
     *
     * @mbg.generated
     */
    @Delete({
        "delete from sys_role_url",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_url
     *
     * @mbg.generated
     */
    @Insert({
        "insert into sys_role_url (role_id, url_id)",
        "values (#{roleId,jdbcType=INTEGER}, #{urlId,jdbcType=INTEGER})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(SysRoleUrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_url
     *
     * @mbg.generated
     */
    int insertSelective(SysRoleUrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_url
     *
     * @mbg.generated
     */
    List<SysRoleUrl> selectByExample(SysRoleUrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_url
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, role_id, url_id",
        "from sys_role_url",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.yuudati.securitydemo.dao.SysRoleUrlMapper.BaseResultMap")
    SysRoleUrl selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_url
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SysRoleUrl record, @Param("example") SysRoleUrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_url
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SysRoleUrl record, @Param("example") SysRoleUrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_url
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysRoleUrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_url
     *
     * @mbg.generated
     */
    @Update({
        "update sys_role_url",
        "set role_id = #{roleId,jdbcType=INTEGER},",
          "url_id = #{urlId,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(SysRoleUrl record);
}