package com.yuudati.securitydemo.pojo;

public class SysRoleUrl {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_url.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_url.role_id
     *
     * @mbg.generated
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_url.url_id
     *
     * @mbg.generated
     */
    private Integer urlId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_url
     *
     * @mbg.generated
     */
    public SysRoleUrl(Integer id, Integer roleId, Integer urlId) {
        this.id = id;
        this.roleId = roleId;
        this.urlId = urlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_url
     *
     * @mbg.generated
     */
    public SysRoleUrl() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_url.id
     *
     * @return the value of sys_role_url.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_url.id
     *
     * @param id the value for sys_role_url.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_url.role_id
     *
     * @return the value of sys_role_url.role_id
     *
     * @mbg.generated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_url.role_id
     *
     * @param roleId the value for sys_role_url.role_id
     *
     * @mbg.generated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_url.url_id
     *
     * @return the value of sys_role_url.url_id
     *
     * @mbg.generated
     */
    public Integer getUrlId() {
        return urlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_url.url_id
     *
     * @param urlId the value for sys_role_url.url_id
     *
     * @mbg.generated
     */
    public void setUrlId(Integer urlId) {
        this.urlId = urlId;
    }
}